# Generated by Django 4.1 on 2022-08-09 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_hospital_delete_territory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Hospital Name'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('M', 'Montage'), ('N', 'Neuro Combo 1.5mm'), ('Q', 'Rib Fix Advantage'), ('R', 'Rib Fix Blu'), ('S', 'Sternalock Blu'), ('T', 'Thin Flap Neuro 1.5mm'), ('U', 'Trauma One')], default='M', max_length=100)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.hospital')),
            ],
        ),
    ]
