# Generated by Django 4.1 on 2022-08-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_hospital_name_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('C', 'Consignment'), ('L', 'Loaner')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(choices=[('M', 'Montage'), ('N', 'Neuro Combo 1.5mm'), ('Q', 'Rib Fix Advantage'), ('R', 'Rib Fix Blu'), ('S', 'Sternalock Blu'), ('T', 'Thin Flap Neuro 1.5mm'), ('U', 'Trauma One')], default='M', max_length=1),
        ),
    ]
