# Generated by Django 4.1 on 2022-08-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
